
package com.conference.gui.presentation;


import com.conference.gui.clients.IRestConference;
import com.conference.gui.entities.Conferencia;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.time.temporal.ChronoUnit;
import javax.swing.JOptionPane;
/**
 * Interfaz para asignar un evaluador a un paper.
 * 
* @author Maria Paula Barrera
 * @author Ashlee Vanessa Campaz
 * @author Monica Alejandra Castellanos
 * @author Karold Dirley Delgado
 * @author William Andres Serna
 * @version 1.0
 * @since 2024
 */
public class GUIassignEvaluator extends javax.swing.JInternalFrame {
        // Variable para almacenar el último mensaje de diálogo
    private String lastDialogMessage;
    

    // Método para mostrar el diálogo y almacenar el mensaje
    public void showMessage(String message) {
        JOptionPane.showMessageDialog(null, message);
        lastDialogMessage = message;  // Guardar el mensaje
    }

    // Método para obtener el último mensaje
    public String getLastDialogMessage() {
        return lastDialogMessage;
    }

    /**
     * Creates new form GUIcreateConference
     */
       private IRestConference conferenceService;

      

    

    public GUIassignEvaluator(IRestConference con) {
        this.conferenceService = con;
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlInferior = new javax.swing.JPanel();
        pnlRepArticulos = new javax.swing.JPanel();
        jLabelEvaluDisponibles = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListEvaluDisponible = new javax.swing.JList<>();
        jButtonAsignarEvaluador = new javax.swing.JButton();
        jButtonActualizarEvaluadores = new javax.swing.JButton();
        pnlEvArticulos = new javax.swing.JPanel();
        jLabelEvaluAsignados = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEvaluAsignado = new javax.swing.JList<>();
        jButtonEliminarEvaluadorAsignado = new javax.swing.JButton();
        pnlAsigEvaluador = new javax.swing.JLabel();
        pnlSuperior = new javax.swing.JPanel();
        pnlInfoGeneral = new javax.swing.JPanel();
        pnlSeleccioneArticulo = new javax.swing.JLabel();
        jComboBoxArticulos = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDetallesArticulo = new javax.swing.JTextArea();
        jButtonDetalleArticulo = new javax.swing.JButton();
        pnlBotonGuardar = new javax.swing.JPanel();
        lbGuardar1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(229, 229, 229));
        setBorder(null);
        setToolTipText("");
        setFrameIcon(null);
        setMinimumSize(new java.awt.Dimension(873, 650));
        setPreferredSize(new java.awt.Dimension(873, 650));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnlInferior.setBackground(new java.awt.Color(255, 255, 255));

        pnlRepArticulos.setBackground(new java.awt.Color(255, 255, 255));

        jLabelEvaluDisponibles.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N
        jLabelEvaluDisponibles.setForeground(new java.awt.Color(51, 51, 51));
        jLabelEvaluDisponibles.setText("Evaluadores Disponibles");

        jListEvaluDisponible.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListEvaluDisponible);

        jButtonAsignarEvaluador.setText("Asignar");

        jButtonActualizarEvaluadores.setText("Actualizar");

        javax.swing.GroupLayout pnlRepArticulosLayout = new javax.swing.GroupLayout(pnlRepArticulos);
        pnlRepArticulos.setLayout(pnlRepArticulosLayout);
        pnlRepArticulosLayout.setHorizontalGroup(
            pnlRepArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRepArticulosLayout.createSequentialGroup()
                .addGroup(pnlRepArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEvaluDisponibles)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRepArticulosLayout.createSequentialGroup()
                        .addComponent(jButtonActualizarEvaluadores)
                        .addGap(36, 36, 36)
                        .addComponent(jButtonAsignarEvaluador)))
                .addGap(0, 103, Short.MAX_VALUE))
        );
        pnlRepArticulosLayout.setVerticalGroup(
            pnlRepArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRepArticulosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEvaluDisponibles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlRepArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAsignarEvaluador)
                    .addComponent(jButtonActualizarEvaluadores))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlEvArticulos.setBackground(new java.awt.Color(255, 255, 255));

        jLabelEvaluAsignados.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N
        jLabelEvaluAsignados.setForeground(new java.awt.Color(51, 51, 51));
        jLabelEvaluAsignados.setText("Evaluadores Asignados");

        jListEvaluAsignado.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListEvaluAsignado);

        jButtonEliminarEvaluadorAsignado.setText("Eliminar");

        javax.swing.GroupLayout pnlEvArticulosLayout = new javax.swing.GroupLayout(pnlEvArticulos);
        pnlEvArticulos.setLayout(pnlEvArticulosLayout);
        pnlEvArticulosLayout.setHorizontalGroup(
            pnlEvArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEvArticulosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEvArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEvaluAsignados)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminarEvaluadorAsignado))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        pnlEvArticulosLayout.setVerticalGroup(
            pnlEvArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEvArticulosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEvaluAsignados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonEliminarEvaluadorAsignado)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlInferiorLayout = new javax.swing.GroupLayout(pnlInferior);
        pnlInferior.setLayout(pnlInferiorLayout);
        pnlInferiorLayout.setHorizontalGroup(
            pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInferiorLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(pnlRepArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlEvArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlInferiorLayout.setVerticalGroup(
            pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlEvArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRepArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 80, 0, 50);
        getContentPane().add(pnlInferior, gridBagConstraints);

        pnlAsigEvaluador.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        pnlAsigEvaluador.setForeground(new java.awt.Color(102, 102, 102));
        pnlAsigEvaluador.setText("Asignar Evaluadores a un Articulo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 80, 0, 0);
        getContentPane().add(pnlAsigEvaluador, gridBagConstraints);

        pnlSuperior.setBackground(new java.awt.Color(255, 255, 255));

        pnlInfoGeneral.setBackground(new java.awt.Color(255, 255, 255));

        pnlSeleccioneArticulo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N
        pnlSeleccioneArticulo.setForeground(new java.awt.Color(51, 51, 51));
        pnlSeleccioneArticulo.setText("Seleccione un articulo:");

        jComboBoxArticulos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextAreaDetallesArticulo.setColumns(20);
        jTextAreaDetallesArticulo.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDetallesArticulo);

        jButtonDetalleArticulo.setText("Ver Detalles");

        javax.swing.GroupLayout pnlInfoGeneralLayout = new javax.swing.GroupLayout(pnlInfoGeneral);
        pnlInfoGeneral.setLayout(pnlInfoGeneralLayout);
        pnlInfoGeneralLayout.setHorizontalGroup(
            pnlInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlInfoGeneralLayout.createSequentialGroup()
                        .addComponent(pnlSeleccioneArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jButtonDetalleArticulo))
                    .addComponent(jScrollPane2))
                .addGap(0, 114, Short.MAX_VALUE))
        );
        pnlInfoGeneralLayout.setVerticalGroup(
            pnlInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoGeneralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnlSeleccioneArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDetalleArticulo))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout pnlSuperiorLayout = new javax.swing.GroupLayout(pnlSuperior);
        pnlSuperior.setLayout(pnlSuperiorLayout);
        pnlSuperiorLayout.setHorizontalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSuperiorLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(pnlInfoGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        pnlSuperiorLayout.setVerticalGroup(
            pnlSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInfoGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 80, 0, 50);
        getContentPane().add(pnlSuperior, gridBagConstraints);

        pnlBotonGuardar.setBackground(new java.awt.Color(255, 255, 255));
        pnlBotonGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlBotonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBotonGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBotonGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBotonGuardarMouseExited(evt);
            }
        });

        lbGuardar1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lbGuardar1.setText("Guardar");

        javax.swing.GroupLayout pnlBotonGuardarLayout = new javax.swing.GroupLayout(pnlBotonGuardar);
        pnlBotonGuardar.setLayout(pnlBotonGuardarLayout);
        pnlBotonGuardarLayout.setHorizontalGroup(
            pnlBotonGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonGuardarLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbGuardar1)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pnlBotonGuardarLayout.setVerticalGroup(
            pnlBotonGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonGuardarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbGuardar1)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 488, 7, 50);
        getContentPane().add(pnlBotonGuardar, gridBagConstraints);

        backButton.setText("Atras");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        getContentPane().add(backButton, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlBotonGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBotonGuardarMouseExited
       lbGuardar1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14));
    }//GEN-LAST:event_pnlBotonGuardarMouseExited

    private void pnlBotonGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBotonGuardarMouseEntered
        lbGuardar1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14));
    }//GEN-LAST:event_pnlBotonGuardarMouseEntered

    private void pnlBotonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBotonGuardarMouseClicked

    }//GEN-LAST:event_pnlBotonGuardarMouseClicked

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton jButtonActualizarEvaluadores;
    private javax.swing.JButton jButtonAsignarEvaluador;
    private javax.swing.JButton jButtonDetalleArticulo;
    private javax.swing.JButton jButtonEliminarEvaluadorAsignado;
    private javax.swing.JComboBox<String> jComboBoxArticulos;
    private javax.swing.JLabel jLabelEvaluAsignados;
    private javax.swing.JLabel jLabelEvaluDisponibles;
    private javax.swing.JList<String> jListEvaluAsignado;
    private javax.swing.JList<String> jListEvaluDisponible;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaDetallesArticulo;
    private javax.swing.JLabel lbGuardar1;
    private javax.swing.JLabel pnlAsigEvaluador;
    private javax.swing.JPanel pnlBotonGuardar;
    private javax.swing.JPanel pnlEvArticulos;
    private javax.swing.JPanel pnlInferior;
    private javax.swing.JPanel pnlInfoGeneral;
    private javax.swing.JPanel pnlRepArticulos;
    private javax.swing.JLabel pnlSeleccioneArticulo;
    private javax.swing.JPanel pnlSuperior;
    // End of variables declaration//GEN-END:variables
}
