/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.conference.gui.presentation;

import com.conference.gui.entities.Conferencia;
import java.awt.Dimension;
import java.util.List;
import javax.swing.BoxLayout;

/**
 *
 * @author wsern
 */
public class GUIconferenceSearch extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     * @param conferences
     */
 public GUIconferenceSearch(List<Conferencia> conferences) {
    initComponents(); // Carga la interfaz gráfica diseñada en NetBeans

    // Limpia cualquier contenido previo en el panel `pnlResultados`
    pnlResultados.removeAll();
    pnlResultados.setLayout(new BoxLayout(pnlResultados, BoxLayout.Y_AXIS)); // Diseño vertical para resultados dinámicos

    // Itera sobre las conferencias y agrega un `pnlConferenceInfo` por cada una
    for (Conferencia conference : conferences) {
        pnlConferenceInfo conferenceInfoPanel = new pnlConferenceInfo(conference);

        // Ajusta el tamaño del panel aquí (solo altura fija, el ancho lo manejará automáticamente)
        conferenceInfoPanel.setPreferredSize(new Dimension(pnlResultados.getWidth()-100, 60)); // Ancho dinámico, altura fija
        conferenceInfoPanel.setMaximumSize(new Dimension(Integer.MAX_VALUE, 60)); // Permite ajuste dinámico de ancho, fija altura
        conferenceInfoPanel.setMinimumSize(new Dimension(0, 60)); // Altura fija con ancho mínimo 0 para evitar problemas

        pnlResultados.add(conferenceInfoPanel); // Agrega al panel
    }

    // Revalida y redibuja el panel para mostrar los cambios
    pnlResultados.revalidate();
    pnlResultados.repaint();
}
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlCamposConferencia = new javax.swing.JPanel();
        lbNombre = new javax.swing.JLabel();
        lbPais = new javax.swing.JLabel();
        lbCiudad = new javax.swing.JLabel();
        lbTemas = new javax.swing.JLabel();
        scpConBusqueda = new javax.swing.JScrollPane();
        pnlResultados = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pnlCamposConferencia.setBackground(new java.awt.Color(0, 204, 204));

        lbNombre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbNombre.setForeground(new java.awt.Color(255, 255, 255));
        lbNombre.setText("Nombre");

        lbPais.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbPais.setForeground(new java.awt.Color(255, 255, 255));
        lbPais.setText("Pais");

        lbCiudad.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbCiudad.setForeground(new java.awt.Color(255, 255, 255));
        lbCiudad.setText("Ciudad");

        lbTemas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbTemas.setForeground(new java.awt.Color(255, 255, 255));
        lbTemas.setText("Temas");

        javax.swing.GroupLayout pnlCamposConferenciaLayout = new javax.swing.GroupLayout(pnlCamposConferencia);
        pnlCamposConferencia.setLayout(pnlCamposConferenciaLayout);
        pnlCamposConferenciaLayout.setHorizontalGroup(
            pnlCamposConferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCamposConferenciaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbNombre)
                .addGap(127, 127, 127)
                .addComponent(lbPais)
                .addGap(134, 134, 134)
                .addComponent(lbCiudad)
                .addGap(121, 121, 121)
                .addComponent(lbTemas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCamposConferenciaLayout.setVerticalGroup(
            pnlCamposConferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCamposConferenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCamposConferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre)
                    .addComponent(lbPais)
                    .addComponent(lbCiudad)
                    .addComponent(lbTemas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scpConBusqueda.setBackground(new java.awt.Color(255, 255, 255));

        pnlResultados.setBackground(new java.awt.Color(255, 255, 255));
        pnlResultados.setLayout(new javax.swing.BoxLayout(pnlResultados, javax.swing.BoxLayout.LINE_AXIS));
        scpConBusqueda.setViewportView(pnlResultados);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpConBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
            .addComponent(pnlCamposConferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(pnlCamposConferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpConBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCiudad;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbPais;
    private javax.swing.JLabel lbTemas;
    private javax.swing.JPanel pnlCamposConferencia;
    private javax.swing.JPanel pnlResultados;
    private javax.swing.JScrollPane scpConBusqueda;
    // End of variables declaration//GEN-END:variables
}
