/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.conference.gui.presentation;

/**
 *
 * @author Ashlee Campaz
 */
public class GUIconferenceChair extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIconferenceChair
     */
    public GUIconferenceChair() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbGestionConferencia = new javax.swing.JLabel();
        lbConferenceName = new javax.swing.JLabel();
        pnlInfoArticulos = new javax.swing.JPanel();
        lbNumArtEnviados = new javax.swing.JLabel();
        lbNumArtEvaluados = new javax.swing.JLabel();
        pnlConferenceInfo = new javax.swing.JPanel();
        lbFechaInicio = new javax.swing.JLabel();
        lbFechaFin = new javax.swing.JLabel();
        lbFechaRepArt = new javax.swing.JLabel();
        lbFechaEvaluaciones = new javax.swing.JLabel();
        lbPais = new javax.swing.JLabel();
        lbEstado = new javax.swing.JLabel();
        lbCiudad = new javax.swing.JLabel();
        lbDireccion = new javax.swing.JLabel();
        pnlBtnMatching = new javax.swing.JPanel();
        lbMatching = new javax.swing.JLabel();

        setBackground(new java.awt.Color(229, 229, 229));
        setBorder(null);
        setFrameIcon(null);
        setMinimumSize(new java.awt.Dimension(873, 650));
        setPreferredSize(new java.awt.Dimension(873, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbGestionConferencia.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lbGestionConferencia.setForeground(new java.awt.Color(102, 102, 102));
        lbGestionConferencia.setText("Gestion Conferencia");
        getContentPane().add(lbGestionConferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 14, -1, -1));

        lbConferenceName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lbConferenceName.setForeground(new java.awt.Color(102, 102, 102));
        lbConferenceName.setText("conference_name");
        getContentPane().add(lbConferenceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 80, -1, -1));

        pnlInfoArticulos.setBackground(new java.awt.Color(255, 255, 255));

        lbNumArtEnviados.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lbNumArtEnviados.setText("Numero articulos enviados: #/#");

        lbNumArtEvaluados.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lbNumArtEvaluados.setText("Numero articulos evaluados: #/#");

        javax.swing.GroupLayout pnlInfoArticulosLayout = new javax.swing.GroupLayout(pnlInfoArticulos);
        pnlInfoArticulos.setLayout(pnlInfoArticulosLayout);
        pnlInfoArticulosLayout.setHorizontalGroup(
            pnlInfoArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoArticulosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlInfoArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNumArtEvaluados)
                    .addComponent(lbNumArtEnviados))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        pnlInfoArticulosLayout.setVerticalGroup(
            pnlInfoArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoArticulosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbNumArtEnviados)
                .addGap(27, 27, 27)
                .addComponent(lbNumArtEvaluados)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(pnlInfoArticulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 111, 345, -1));

        pnlConferenceInfo.setBackground(new java.awt.Color(255, 255, 255));

        lbFechaInicio.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lbFechaInicio.setText("Inicio: DD/MM/AAAA");

        lbFechaFin.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lbFechaFin.setText("Fin: DD/MM/AAAA");

        lbFechaRepArt.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lbFechaRepArt.setText("Recepcion de articulos hasta: DD/MM/AAAA");

        lbFechaEvaluaciones.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lbFechaEvaluaciones.setText("Evaluaciones: DD/MM/AAAA");

        lbPais.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lbPais.setText("Pais: ####");

        lbEstado.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lbEstado.setText("Provincia/Estado: ####");

        lbCiudad.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lbCiudad.setText("Cuidad: ####");

        lbDireccion.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        lbDireccion.setText("Direccion: ####");
        lbDireccion.setToolTipText("");

        javax.swing.GroupLayout pnlConferenceInfoLayout = new javax.swing.GroupLayout(pnlConferenceInfo);
        pnlConferenceInfo.setLayout(pnlConferenceInfoLayout);
        pnlConferenceInfoLayout.setHorizontalGroup(
            pnlConferenceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConferenceInfoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlConferenceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbFechaInicio)
                    .addComponent(lbFechaEvaluaciones)
                    .addComponent(lbFechaRepArt)
                    .addComponent(lbFechaFin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(pnlConferenceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPais)
                    .addComponent(lbEstado)
                    .addComponent(lbCiudad)
                    .addComponent(lbDireccion))
                .addGap(85, 85, 85))
        );
        pnlConferenceInfoLayout.setVerticalGroup(
            pnlConferenceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConferenceInfoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlConferenceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFechaInicio)
                    .addComponent(lbPais))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConferenceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFechaFin)
                    .addComponent(lbEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConferenceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFechaRepArt)
                    .addComponent(lbCiudad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConferenceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFechaEvaluaciones)
                    .addComponent(lbDireccion))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(pnlConferenceInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 580, -1));

        pnlBtnMatching.setBackground(new java.awt.Color(129, 218, 199));
        pnlBtnMatching.setLayout(new java.awt.BorderLayout());

        lbMatching.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbMatching.setForeground(new java.awt.Color(255, 255, 255));
        lbMatching.setText("         Proceso de Matching             ");
        pnlBtnMatching.add(lbMatching, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlBtnMatching, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 111, -1, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbCiudad;
    private javax.swing.JLabel lbConferenceName;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbFechaEvaluaciones;
    private javax.swing.JLabel lbFechaFin;
    private javax.swing.JLabel lbFechaInicio;
    private javax.swing.JLabel lbFechaRepArt;
    private javax.swing.JLabel lbGestionConferencia;
    private javax.swing.JLabel lbMatching;
    private javax.swing.JLabel lbNumArtEnviados;
    private javax.swing.JLabel lbNumArtEvaluados;
    private javax.swing.JLabel lbPais;
    private javax.swing.JPanel pnlBtnMatching;
    private javax.swing.JPanel pnlConferenceInfo;
    private javax.swing.JPanel pnlInfoArticulos;
    // End of variables declaration//GEN-END:variables
}
