/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.conference.gui.presentation;

import com.conference.gui.entities.Conference;
import java.util.List;

/**
 *
 * @author Ashlee Campaz
 */
public class GUIconferenceResearch extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIconferenceResearch
     */
    
    private List<Conference> searchResults;
    private List<pnlConferenceInfo> searchResultsPanels; 
    public GUIconferenceResearch(List<Conference> searchResults) {
        this.searchResults = searchResults;
        initComponents();
    }

    public void buildResultPanels(){
        
        for(Conference c: searchResults){
            pnlConferenceInfo infoConference = new pnlConferenceInfo(c); 
            searchResultsPanels.add(infoConference);
            pnlResultados.add(infoConference);
        }
        pnlResultados.revalidate();
        pnlResultados.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCamposConferencia = new javax.swing.JPanel();
        lbNombre = new javax.swing.JLabel();
        lbPais = new javax.swing.JLabel();
        lbCiudad = new javax.swing.JLabel();
        lbTemas = new javax.swing.JLabel();
        scpConBusqueda = new javax.swing.JScrollPane();
        pnlResultados = new javax.swing.JPanel();

        setBorder(null);
        setFrameIcon(null);

        pnlCamposConferencia.setBackground(new java.awt.Color(0, 204, 204));

        lbNombre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbNombre.setForeground(new java.awt.Color(255, 255, 255));
        lbNombre.setText("Nombre");

        lbPais.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbPais.setForeground(new java.awt.Color(255, 255, 255));
        lbPais.setText("Pais");

        lbCiudad.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbCiudad.setForeground(new java.awt.Color(255, 255, 255));
        lbCiudad.setText("Ciudad");

        lbTemas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbTemas.setForeground(new java.awt.Color(255, 255, 255));
        lbTemas.setText("Temas");

        javax.swing.GroupLayout pnlCamposConferenciaLayout = new javax.swing.GroupLayout(pnlCamposConferencia);
        pnlCamposConferencia.setLayout(pnlCamposConferenciaLayout);
        pnlCamposConferenciaLayout.setHorizontalGroup(
            pnlCamposConferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCamposConferenciaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbNombre)
                .addGap(147, 147, 147)
                .addComponent(lbPais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbCiudad)
                .addGap(149, 149, 149)
                .addComponent(lbTemas)
                .addGap(62, 62, 62))
        );
        pnlCamposConferenciaLayout.setVerticalGroup(
            pnlCamposConferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCamposConferenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCamposConferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre)
                    .addComponent(lbPais)
                    .addComponent(lbCiudad)
                    .addComponent(lbTemas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scpConBusqueda.setBackground(new java.awt.Color(255, 255, 255));

        pnlResultados.setBackground(new java.awt.Color(255, 255, 255));
        pnlResultados.setLayout(new javax.swing.BoxLayout(pnlResultados, javax.swing.BoxLayout.LINE_AXIS));
        scpConBusqueda.setViewportView(pnlResultados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCamposConferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scpConBusqueda)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlCamposConferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpConBusqueda))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbCiudad;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbPais;
    private javax.swing.JLabel lbTemas;
    private javax.swing.JPanel pnlCamposConferencia;
    private javax.swing.JPanel pnlResultados;
    private javax.swing.JScrollPane scpConBusqueda;
    // End of variables declaration//GEN-END:variables
}
