/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.conference.gui.presentation;

import com.conference.gui.conference.UserConference;
import com.conference.gui.entities.Conference;
import com.conference.gui.presentation.infra.Observer;
import java.util.List;

/**
 *
 * @author Ashlee Campaz
 */
public class GUImisConferencias extends javax.swing.JInternalFrame implements Observer {

    /**
     * Creates new form GUImisConferencias
     */
    private UserConference conferenceClient; 
    private List<Conference> conferencias;
    public GUImisConferencias() {
        initComponents();
    }
    
    public GUImisConferencias(UserConference conferenceClient) {
        this.conferenceClient = conferenceClient;
        initComponents();
        buildResultPanels();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbMisConferencias = new javax.swing.JLabel();
        scrlpConferencias = new javax.swing.JScrollPane();
        pnlConferencias = new javax.swing.JPanel();

        setBorder(null);
        setFrameIcon(null);
        setMinimumSize(new java.awt.Dimension(873, 650));
        setPreferredSize(new java.awt.Dimension(873, 650));

        lbMisConferencias.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        lbMisConferencias.setText("Mis conferencias");

        javax.swing.GroupLayout pnlConferenciasLayout = new javax.swing.GroupLayout(pnlConferencias);
        pnlConferencias.setLayout(pnlConferenciasLayout);
        pnlConferenciasLayout.setHorizontalGroup(
            pnlConferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );
        pnlConferenciasLayout.setVerticalGroup(
            pnlConferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        scrlpConferencias.setViewportView(pnlConferencias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMisConferencias)
                    .addComponent(scrlpConferencias, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lbMisConferencias)
                .addGap(27, 27, 27)
                .addComponent(scrlpConferencias, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void update(Object o) {
        buildResultPanels();    
    }

    private void buildResultPanels(){
        conferencias = conferenceClient.getConferencias();
        for(Conference c: conferencias){
            pnlConferenceInfo infoConference = new pnlConferenceInfo(c); 
            pnlConferencias.add(infoConference);
        }
        pnlConferencias.revalidate();
        pnlConferencias.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbMisConferencias;
    private javax.swing.JPanel pnlConferencias;
    private javax.swing.JScrollPane scrlpConferencias;
    // End of variables declaration//GEN-END:variables
}
