
package com.conference.gui.presentation;


import com.conference.gui.clients.IUserRestClient;
import com.conference.gui.clients.UserClient;
import com.conference.gui.entities.Usuario;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.SpringLayout;

import  javax.swing.JOptionPane;
import org.springframework.amqp.core.Queue;
import org.springframework.amqp.rabbit.annotation.EnableRabbit;
import org.springframework.amqp.rabbit.annotation.RabbitListener;
import org.springframework.amqp.rabbit.core.RabbitTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

/**
 * Interfaz registro
 * 
 * @author 
 * @version 1.0
 * @since 2024
 */

public class GUIregister extends javax.swing.JFrame {
    
     private IUserRestClient userclient; 
    
    
   public GUIregister(IUserRestClient userclient) {
        initComponents();
        setupEventListeners();
        this.userclient = userclient;
    }
    
    private void setupEventListeners() {
        btnRegistrar.addActionListener(e -> handleRegistration());
        
    }
    
    private void handleRegistration() {
        String name = txtfNombre.getText();
        String lastName = txtfApellido.getText();
        String email = txtfCorreo.getText();
        String password = String.valueOf(pswdfConContrasenia.getPassword()) ;
        String confirmPassword = String.valueOf(pswdfConContrasenia.getPassword()) ;
        String country = txtfPais.getText();
        String organization = txtfOrganizacion.getText();
        String fields = txtaCamposInv.getText();
        List<String> fiels = Arrays.asList( txtaCamposInv.getText().split(","));
        // Validate that the passwords match
        if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Usuario us = new Usuario (name,lastName, country, email, organization,  password, new ArrayList<String>(fiels)); 
        Boolean result = userclient.register(us);
        // Handle successful registration
        if (result) {
            clearFields();  // Clear form fields after successful registration
            JOptionPane.showMessageDialog(this, "Usuario registrado con éxito.", "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "El email ya está registrado. Intente con otro.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    
    
    private void clearFields() {
        txtfNombre.setText("");
        txtfNombre.setText("");
        txtfCorreo.setText("");
        pswdfContrasenia.setText("");
        pswdfConContrasenia.setText("");
        txtfPais.setText("");
        txtfApellido.setText("");
        txtfOrganizacion.setText("");
        txtaCamposInv.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlFondo = new javax.swing.JPanel();
        pnlSuperior = new javax.swing.JPanel();
        lbEasyConference = new javax.swing.JLabel();
        pnlFormulario = new javax.swing.JPanel();
        txtfPais = new javax.swing.JTextField();
        txtfNombre = new javax.swing.JTextField();
        txtfCorreo = new javax.swing.JTextField();
        txtfOrganizacion = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        lbYatienesCuenta = new javax.swing.JLabel();
        sclpCamposInv = new javax.swing.JScrollPane();
        txtaCamposInv = new javax.swing.JTextArea();
        txtfApellido = new javax.swing.JTextField();
        lbMostrarContrasenia = new javax.swing.JLabel();
        pswdfConContrasenia = new javax.swing.JPasswordField();
        pswdfContrasenia = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(682, 542));
        setSize(new java.awt.Dimension(784, 649));

        pnlFondo.setBackground(new java.awt.Color(255, 255, 255));

        pnlSuperior.setBackground(new java.awt.Color(0, 153, 153));
        pnlSuperior.setPreferredSize(new java.awt.Dimension(192, 52));
        pnlSuperior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        lbEasyConference.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lbEasyConference.setForeground(new java.awt.Color(255, 255, 255));
        lbEasyConference.setText("easyConference");
        pnlSuperior.add(lbEasyConference);

        pnlFormulario.setBackground(new java.awt.Color(255, 255, 255));
        pnlFormulario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 24), new java.awt.Color(0, 153, 153))); // NOI18N
        pnlFormulario.setMinimumSize(new java.awt.Dimension(643, 456));
        pnlFormulario.setLayout(new java.awt.GridBagLayout());

        txtfPais.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtfPais.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "*Pais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 12))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BELOW_BASELINE;
        gridBagConstraints.insets = new java.awt.Insets(26, 32, 0, 0);
        pnlFormulario.add(txtfPais, gridBagConstraints);

        txtfNombre.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtfNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "*Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 12))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(18, 32, 0, 0);
        pnlFormulario.add(txtfNombre, gridBagConstraints);

        txtfCorreo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtfCorreo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "*Correo electronico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 12))); // NOI18N
        txtfCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfCorreoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(18, 32, 0, 0);
        pnlFormulario.add(txtfCorreo, gridBagConstraints);

        txtfOrganizacion.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtfOrganizacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "*Organizacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 12))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 151;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(18, 32, 0, 0);
        pnlFormulario.add(txtfOrganizacion, gridBagConstraints);

        btnRegistrar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 66, 20, 16);
        pnlFormulario.add(btnRegistrar, gridBagConstraints);

        lbYatienesCuenta.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        lbYatienesCuenta.setForeground(new java.awt.Color(0, 102, 102));
        lbYatienesCuenta.setText("¿Ya tienes cuenta? De clic aquí");
        lbYatienesCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbYatienesCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbYatienesCuentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbYatienesCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbYatienesCuentaMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(24, 32, 0, 0);
        pnlFormulario.add(lbYatienesCuenta, gridBagConstraints);

        txtaCamposInv.setColumns(20);
        txtaCamposInv.setLineWrap(true);
        txtaCamposInv.setRows(5);
        txtaCamposInv.setWrapStyleWord(true);
        txtaCamposInv.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "*Campos de investigacion"));
        sclpCamposInv.setViewportView(txtaCamposInv);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(28, 34, 28, 34);
        pnlFormulario.add(sclpCamposInv, gridBagConstraints);

        txtfApellido.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        txtfApellido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "*Apellido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 12))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(18, 32, 0, 0);
        pnlFormulario.add(txtfApellido, gridBagConstraints);

        lbMostrarContrasenia.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        lbMostrarContrasenia.setText("clic aqui para mostrar contraseña");
        lbMostrarContrasenia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMostrarContraseniaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMostrarContraseniaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbMostrarContraseniaMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(0, 31, 0, 0);
        pnlFormulario.add(lbMostrarContrasenia, gridBagConstraints);

        pswdfConContrasenia.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        pswdfConContrasenia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "*Confirmar contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 12))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(18, 32, 0, 0);
        pnlFormulario.add(pswdfConContrasenia, gridBagConstraints);

        pswdfContrasenia.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        pswdfContrasenia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "*Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 0, 12))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(18, 32, 0, 0);
        pnlFormulario.add(pswdfContrasenia, gridBagConstraints);

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(pnlFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addComponent(pnlSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(pnlFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        getContentPane().add(pnlSuperior, java.awt.BorderLayout.NORTH);

        getContentPane().add(pnlFondo, java.awt.BorderLayout.CENTER);
        SpringLayout centrador = new SpringLayout();
        centrador.putConstraint(SpringLayout.VERTICAL_CENTER, pnlFormulario, 20, SpringLayout.VERTICAL_CENTER, pnlFondo);
        centrador.putConstraint(SpringLayout.HORIZONTAL_CENTER, pnlFormulario, 20, SpringLayout.HORIZONTAL_CENTER, pnlFondo);
        centrador.putConstraint(SpringLayout.WIDTH, pnlFormulario, 20, SpringLayout.HEIGHT, pnlFondo);
        pnlFondo.setLayout(centrador);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtfNombreActionPerformed(java.awt.event.ActionEvent evt) {                                           
        txtfNombre.requestFocus(); 
    }                                          

    private void lbYatienesCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbYatienesCuentaMouseEntered
        lbYatienesCuenta.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12));
    }//GEN-LAST:event_lbYatienesCuentaMouseEntered
    
    private void lbYatienesCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbYatienesCuentaMouseExited
        lbYatienesCuenta.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12));
    }//GEN-LAST:event_lbYatienesCuentaMouseExited
    
   

    private void lbYatienesCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbYatienesCuentaMouseClicked
        this.dispose();
        UserClient userclient = new UserClient(); 
        GUIlogin login = new GUIlogin(userclient); 
        login.setLocationRelativeTo(null);
        login.setVisible(true);
    }//GEN-LAST:event_lbYatienesCuentaMouseClicked

    private void txtfCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfCorreoActionPerformed
        pswdfContrasenia.requestFocus();
    }//GEN-LAST:event_txtfCorreoActionPerformed

    private void cmbPaisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaisesActionPerformed
        txtfOrganizacion.requestFocus();
    }//GEN-LAST:event_cmbPaisesActionPerformed

    private void txtfApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfApellido1ActionPerformed

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void lbMostrarContraseniaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMostrarContraseniaMouseEntered
     lbMostrarContrasenia.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12));
    }//GEN-LAST:event_lbMostrarContraseniaMouseEntered

    private void lbMostrarContraseniaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMostrarContraseniaMouseExited
       lbMostrarContrasenia.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12));
    }//GEN-LAST:event_lbMostrarContraseniaMouseExited

    private void lbMostrarContraseniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMostrarContraseniaMouseClicked
        if (pswdfContrasenia.getEchoChar() == 0) {
            pswdfContrasenia.setEchoChar('•');
            pswdfConContrasenia.setEchoChar('•');
        } else {
            pswdfContrasenia.setEchoChar((char) 0);
            pswdfConContrasenia.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_lbMostrarContraseniaMouseClicked

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel lbEasyConference;
    private javax.swing.JLabel lbMostrarContrasenia;
    private javax.swing.JLabel lbYatienesCuenta;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JPanel pnlSuperior;
    private javax.swing.JPasswordField pswdfConContrasenia;
    private javax.swing.JPasswordField pswdfContrasenia;
    private javax.swing.JScrollPane sclpCamposInv;
    private javax.swing.JTextArea txtaCamposInv;
    private javax.swing.JTextField txtfApellido;
    private javax.swing.JTextField txtfCorreo;
    private javax.swing.JTextField txtfNombre;
    private javax.swing.JTextField txtfOrganizacion;
    private javax.swing.JTextField txtfPais;
    // End of variables declaration//GEN-END:variables
}
